// Pronunciation data for all supported languages
// Each language has alphabet/characters, basic words, and beginner sentences

export interface PronunciationItem {
  text: string;
  phonetic: string;
  translation: string;
}

export interface LanguagePronunciationData {
  speechLang: string; // BCP-47 code for Web Speech API
  ttsLang: string;    // BCP-47 code for TTS
  alphabet: PronunciationItem[];
  words: PronunciationItem[];
  sentences: PronunciationItem[];
}

// Map language_code (from DB) -> pronunciation data
export const PRONUNCIATION_DATA: Record<string, LanguagePronunciationData> = {
  es: {
    speechLang: 'es-ES',
    ttsLang: 'es-ES',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'beh', translation: 'B' },
      { text: 'C', phonetic: 'seh', translation: 'C' },
      { text: 'D', phonetic: 'deh', translation: 'D' },
      { text: 'E', phonetic: 'eh', translation: 'E' },
      { text: 'F', phonetic: 'EH-feh', translation: 'F' },
      { text: 'G', phonetic: 'heh', translation: 'G' },
      { text: 'H', phonetic: 'AH-cheh', translation: 'H' },
      { text: 'I', phonetic: 'ee', translation: 'I' },
      { text: 'J', phonetic: 'HOH-tah', translation: 'J' },
      { text: 'K', phonetic: 'kah', translation: 'K' },
      { text: 'L', phonetic: 'EH-leh', translation: 'L' },
      { text: 'M', phonetic: 'EH-meh', translation: 'M' },
      { text: 'N', phonetic: 'EH-neh', translation: 'N' },
      { text: 'Ñ', phonetic: 'EH-nyeh', translation: 'Ñ' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'peh', translation: 'P' },
      { text: 'Q', phonetic: 'koo', translation: 'Q' },
      { text: 'R', phonetic: 'EH-reh', translation: 'R' },
      { text: 'S', phonetic: 'EH-seh', translation: 'S' },
      { text: 'T', phonetic: 'teh', translation: 'T' },
      { text: 'U', phonetic: 'oo', translation: 'U' },
      { text: 'V', phonetic: 'oo-beh', translation: 'V' },
      { text: 'W', phonetic: 'DOH-bleh oo', translation: 'W' },
      { text: 'X', phonetic: 'EH-kees', translation: 'X' },
      { text: 'Y', phonetic: 'ee GREE-eh-gah', translation: 'Y' },
      { text: 'Z', phonetic: 'SEH-tah', translation: 'Z' },
    ],
    words: [
      { text: 'hola', phonetic: 'OH-lah', translation: 'hello' },
      { text: 'gracias', phonetic: 'GRAH-syahs', translation: 'thank you' },
      { text: 'buenos días', phonetic: 'BWEH-nohs DEE-ahs', translation: 'good morning' },
      { text: 'por favor', phonetic: 'pohr fah-BOHR', translation: 'please' },
      { text: 'adiós', phonetic: 'ah-DYOHS', translation: 'goodbye' },
      { text: 'amigo', phonetic: 'ah-MEE-goh', translation: 'friend' },
      { text: 'agua', phonetic: 'AH-gwah', translation: 'water' },
      { text: 'comida', phonetic: 'koh-MEE-dah', translation: 'food' },
      { text: 'casa', phonetic: 'KAH-sah', translation: 'house' },
      { text: 'bueno', phonetic: 'BWEH-noh', translation: 'good' },
      { text: 'grande', phonetic: 'GRAHN-deh', translation: 'big' },
      { text: 'pequeño', phonetic: 'peh-KEH-nyoh', translation: 'small' },
    ],
    sentences: [
      { text: '¿Cómo estás?', phonetic: 'KOH-moh ehs-TAHS', translation: 'How are you?' },
      { text: 'Me llamo María', phonetic: 'meh YAH-moh mah-REE-ah', translation: 'My name is María' },
      { text: 'No entiendo', phonetic: 'noh ehn-TYEHN-doh', translation: "I don't understand" },
      { text: '¿Dónde está el baño?', phonetic: 'DOHN-deh ehs-TAH el BAH-nyoh', translation: 'Where is the bathroom?' },
      { text: 'Mucho gusto', phonetic: 'MOO-choh GOOS-toh', translation: 'Nice to meet you' },
      { text: '¿Cuánto cuesta?', phonetic: 'KWAHN-toh KWEHS-tah', translation: 'How much does it cost?' },
      { text: 'Buenas noches', phonetic: 'BWEH-nahs NOH-chehs', translation: 'Good night' },
      { text: 'Hasta luego', phonetic: 'AHS-tah LWEH-goh', translation: 'See you later' },
    ],
  },

  fr: {
    speechLang: 'fr-FR',
    ttsLang: 'fr-FR',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'beh', translation: 'B' },
      { text: 'C', phonetic: 'seh', translation: 'C' },
      { text: 'D', phonetic: 'deh', translation: 'D' },
      { text: 'E', phonetic: 'uh', translation: 'E' },
      { text: 'F', phonetic: 'eff', translation: 'F' },
      { text: 'G', phonetic: 'zheh', translation: 'G' },
      { text: 'H', phonetic: 'ahsh', translation: 'H' },
      { text: 'I', phonetic: 'ee', translation: 'I' },
      { text: 'J', phonetic: 'zhee', translation: 'J' },
      { text: 'K', phonetic: 'kah', translation: 'K' },
      { text: 'L', phonetic: 'el', translation: 'L' },
      { text: 'M', phonetic: 'em', translation: 'M' },
      { text: 'N', phonetic: 'en', translation: 'N' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'peh', translation: 'P' },
      { text: 'Q', phonetic: 'kew', translation: 'Q' },
      { text: 'R', phonetic: 'air', translation: 'R' },
      { text: 'S', phonetic: 'ess', translation: 'S' },
      { text: 'T', phonetic: 'teh', translation: 'T' },
      { text: 'U', phonetic: 'ew', translation: 'U' },
      { text: 'V', phonetic: 'veh', translation: 'V' },
      { text: 'W', phonetic: 'doo-bluh-veh', translation: 'W' },
      { text: 'X', phonetic: 'eeks', translation: 'X' },
      { text: 'Y', phonetic: 'ee-grek', translation: 'Y' },
      { text: 'Z', phonetic: 'zed', translation: 'Z' },
    ],
    words: [
      { text: 'bonjour', phonetic: 'bohn-ZHOOR', translation: 'hello / good day' },
      { text: 'merci', phonetic: 'mehr-SEE', translation: 'thank you' },
      { text: 'au revoir', phonetic: 'oh ruh-VWAHR', translation: 'goodbye' },
      { text: "s'il vous plaît", phonetic: 'seel voo PLEH', translation: 'please' },
      { text: 'oui', phonetic: 'wee', translation: 'yes' },
      { text: 'non', phonetic: 'nohn', translation: 'no' },
      { text: 'ami', phonetic: 'ah-MEE', translation: 'friend' },
      { text: 'eau', phonetic: 'oh', translation: 'water' },
      { text: 'maison', phonetic: 'meh-ZOHN', translation: 'house' },
      { text: 'bon', phonetic: 'bohn', translation: 'good' },
      { text: 'bonsoir', phonetic: 'bohn-SWAHR', translation: 'good evening' },
      { text: 'excusez-moi', phonetic: 'eks-kew-ZEH mwah', translation: 'excuse me' },
    ],
    sentences: [
      { text: 'Comment allez-vous?', phonetic: 'koh-MAHN tah-leh VOO', translation: 'How are you?' },
      { text: 'Je ne comprends pas', phonetic: 'zhuh nuh kohm-PRAHN pah', translation: "I don't understand" },
      { text: "Je m'appelle Pierre", phonetic: 'zhuh mah-PEL pyehr', translation: 'My name is Pierre' },
      { text: 'Où est la gare?', phonetic: 'oo eh lah gahr', translation: 'Where is the station?' },
      { text: "Combien ça coûte?", phonetic: 'kohm-BYEHN sah koot', translation: 'How much does it cost?' },
      { text: 'Enchanté', phonetic: 'ahn-shahn-TEH', translation: 'Nice to meet you' },
      { text: 'Bonne nuit', phonetic: 'bohn NWEE', translation: 'Good night' },
      { text: 'À bientôt', phonetic: 'ah byehn-TOH', translation: 'See you soon' },
    ],
  },

  ar: {
    speechLang: 'ar-SA',
    ttsLang: 'ar-SA',
    alphabet: [
      { text: 'ا', phonetic: 'alif', translation: 'A' },
      { text: 'ب', phonetic: 'baa', translation: 'B' },
      { text: 'ت', phonetic: 'taa', translation: 'T' },
      { text: 'ث', phonetic: 'thaa', translation: 'Th' },
      { text: 'ج', phonetic: 'jeem', translation: 'J' },
      { text: 'ح', phonetic: 'haa', translation: 'H (deep)' },
      { text: 'خ', phonetic: 'khaa', translation: 'Kh' },
      { text: 'د', phonetic: 'daal', translation: 'D' },
      { text: 'ذ', phonetic: 'dhaal', translation: 'Dh' },
      { text: 'ر', phonetic: 'raa', translation: 'R' },
      { text: 'ز', phonetic: 'zaay', translation: 'Z' },
      { text: 'س', phonetic: 'seen', translation: 'S' },
      { text: 'ش', phonetic: 'sheen', translation: 'Sh' },
      { text: 'ص', phonetic: 'saad', translation: 'S (emphatic)' },
      { text: 'ض', phonetic: 'daad', translation: 'D (emphatic)' },
      { text: 'ط', phonetic: 'taa', translation: 'T (emphatic)' },
      { text: 'ع', phonetic: 'ayn', translation: 'Ayn' },
      { text: 'غ', phonetic: 'ghayn', translation: 'Gh' },
      { text: 'ف', phonetic: 'faa', translation: 'F' },
      { text: 'ق', phonetic: 'qaaf', translation: 'Q' },
      { text: 'ك', phonetic: 'kaaf', translation: 'K' },
      { text: 'ل', phonetic: 'laam', translation: 'L' },
      { text: 'م', phonetic: 'meem', translation: 'M' },
      { text: 'ن', phonetic: 'noon', translation: 'N' },
      { text: 'ه', phonetic: 'haa', translation: 'H' },
      { text: 'و', phonetic: 'waaw', translation: 'W' },
      { text: 'ي', phonetic: 'yaa', translation: 'Y' },
    ],
    words: [
      { text: 'مرحبا', phonetic: 'mar-HA-ba', translation: 'hello' },
      { text: 'شكرا', phonetic: 'SHUK-ran', translation: 'thank you' },
      { text: 'نعم', phonetic: 'NA-am', translation: 'yes' },
      { text: 'لا', phonetic: 'laa', translation: 'no' },
      { text: 'ماء', phonetic: 'maa', translation: 'water' },
      { text: 'طعام', phonetic: 'ta-AAM', translation: 'food' },
      { text: 'بيت', phonetic: 'bayt', translation: 'house' },
      { text: 'صديق', phonetic: 'sa-DEEQ', translation: 'friend' },
      { text: 'كتاب', phonetic: 'ki-TAAB', translation: 'book' },
      { text: 'مدرسة', phonetic: 'mad-RA-sa', translation: 'school' },
      { text: 'سلام', phonetic: 'sa-LAAM', translation: 'peace' },
      { text: 'حب', phonetic: 'hubb', translation: 'love' },
    ],
    sentences: [
      { text: 'كيف حالك؟', phonetic: 'kayf HAA-lak', translation: 'How are you?' },
      { text: 'أنا بخير', phonetic: 'ana bi-KHAYR', translation: 'I am fine' },
      { text: 'ما اسمك؟', phonetic: 'maa IS-mak', translation: 'What is your name?' },
      { text: 'أنا لا أفهم', phonetic: 'ana laa AF-ham', translation: "I don't understand" },
      { text: 'من فضلك', phonetic: 'min FAD-lak', translation: 'please' },
      { text: 'مع السلامة', phonetic: 'ma-a as-sa-LAA-ma', translation: 'goodbye' },
      { text: 'صباح الخير', phonetic: 'sa-BAAH al-KHAYR', translation: 'good morning' },
      { text: 'مساء الخير', phonetic: 'ma-SAA al-KHAYR', translation: 'good evening' },
    ],
  },

  bn: {
    speechLang: 'bn-IN',
    ttsLang: 'bn-IN',
    alphabet: [
      { text: 'অ', phonetic: 'o', translation: 'A/O' },
      { text: 'আ', phonetic: 'aa', translation: 'AA' },
      { text: 'ই', phonetic: 'i', translation: 'I' },
      { text: 'ঈ', phonetic: 'ee', translation: 'EE' },
      { text: 'উ', phonetic: 'u', translation: 'U' },
      { text: 'ঊ', phonetic: 'oo', translation: 'OO' },
      { text: 'ক', phonetic: 'ko', translation: 'K' },
      { text: 'খ', phonetic: 'kho', translation: 'Kh' },
      { text: 'গ', phonetic: 'go', translation: 'G' },
      { text: 'ঘ', phonetic: 'gho', translation: 'Gh' },
      { text: 'চ', phonetic: 'cho', translation: 'Ch' },
      { text: 'ছ', phonetic: 'chho', translation: 'Chh' },
      { text: 'জ', phonetic: 'jo', translation: 'J' },
      { text: 'ঝ', phonetic: 'jho', translation: 'Jh' },
      { text: 'ট', phonetic: 'to', translation: 'T (hard)' },
      { text: 'ড', phonetic: 'do', translation: 'D (hard)' },
      { text: 'ত', phonetic: 'to', translation: 'T (soft)' },
      { text: 'দ', phonetic: 'do', translation: 'D (soft)' },
      { text: 'ন', phonetic: 'no', translation: 'N' },
      { text: 'প', phonetic: 'po', translation: 'P' },
      { text: 'ফ', phonetic: 'pho', translation: 'Ph' },
      { text: 'ব', phonetic: 'bo', translation: 'B' },
      { text: 'ম', phonetic: 'mo', translation: 'M' },
      { text: 'র', phonetic: 'ro', translation: 'R' },
      { text: 'ল', phonetic: 'lo', translation: 'L' },
      { text: 'শ', phonetic: 'sho', translation: 'Sh' },
      { text: 'স', phonetic: 'so', translation: 'S' },
      { text: 'হ', phonetic: 'ho', translation: 'H' },
    ],
    words: [
      { text: 'নমস্কার', phonetic: 'no-MOSH-kar', translation: 'hello' },
      { text: 'ধন্যবাদ', phonetic: 'DHON-no-baad', translation: 'thank you' },
      { text: 'হ্যাঁ', phonetic: 'hyaa', translation: 'yes' },
      { text: 'না', phonetic: 'naa', translation: 'no' },
      { text: 'জল', phonetic: 'jol', translation: 'water' },
      { text: 'খাবার', phonetic: 'KHA-bar', translation: 'food' },
      { text: 'বাড়ি', phonetic: 'BAA-ri', translation: 'house' },
      { text: 'বন্ধু', phonetic: 'BON-dhu', translation: 'friend' },
      { text: 'বই', phonetic: 'boi', translation: 'book' },
      { text: 'ভালো', phonetic: 'BHA-lo', translation: 'good' },
      { text: 'বড়', phonetic: 'bo-ro', translation: 'big' },
      { text: 'ছোট', phonetic: 'CHHO-to', translation: 'small' },
    ],
    sentences: [
      { text: 'আপনি কেমন আছেন?', phonetic: 'aap-ni KE-mon AA-chen', translation: 'How are you?' },
      { text: 'আমার নাম রাহুল', phonetic: 'aa-MAAR naam RA-hul', translation: 'My name is Rahul' },
      { text: 'আমি বুঝতে পারছি না', phonetic: 'aa-mi BUJH-te PAR-chi naa', translation: "I don't understand" },
      { text: 'দয়া করে আস্তে বলুন', phonetic: 'do-YA ko-RE AAS-te BO-lun', translation: 'Please speak slowly' },
      { text: 'এটার দাম কত?', phonetic: 'E-tar DAAM ko-to', translation: 'How much does this cost?' },
      { text: 'শুভ সকাল', phonetic: 'shubh SO-kal', translation: 'Good morning' },
    ],
  },

  pt: {
    speechLang: 'pt-BR',
    ttsLang: 'pt-BR',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'beh', translation: 'B' },
      { text: 'C', phonetic: 'seh', translation: 'C' },
      { text: 'D', phonetic: 'deh', translation: 'D' },
      { text: 'E', phonetic: 'eh', translation: 'E' },
      { text: 'F', phonetic: 'EH-fee', translation: 'F' },
      { text: 'G', phonetic: 'zheh', translation: 'G' },
      { text: 'H', phonetic: 'ah-GAH', translation: 'H' },
      { text: 'I', phonetic: 'ee', translation: 'I' },
      { text: 'J', phonetic: 'ZHOH-tah', translation: 'J' },
      { text: 'K', phonetic: 'kah', translation: 'K' },
      { text: 'L', phonetic: 'EH-lee', translation: 'L' },
      { text: 'M', phonetic: 'EH-mee', translation: 'M' },
      { text: 'N', phonetic: 'EH-nee', translation: 'N' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'peh', translation: 'P' },
      { text: 'Q', phonetic: 'keh', translation: 'Q' },
      { text: 'R', phonetic: 'EH-hee', translation: 'R' },
      { text: 'S', phonetic: 'EH-see', translation: 'S' },
      { text: 'T', phonetic: 'teh', translation: 'T' },
      { text: 'U', phonetic: 'oo', translation: 'U' },
      { text: 'V', phonetic: 'veh', translation: 'V' },
      { text: 'W', phonetic: 'DAH-bloo', translation: 'W' },
      { text: 'X', phonetic: 'sheesh', translation: 'X' },
      { text: 'Y', phonetic: 'EEP-see-lon', translation: 'Y' },
      { text: 'Z', phonetic: 'zeh', translation: 'Z' },
    ],
    words: [
      { text: 'olá', phonetic: 'oh-LAH', translation: 'hello' },
      { text: 'obrigado', phonetic: 'oh-bree-GAH-doo', translation: 'thank you' },
      { text: 'bom dia', phonetic: 'bohm JEE-ah', translation: 'good morning' },
      { text: 'por favor', phonetic: 'pohr fah-VOHR', translation: 'please' },
      { text: 'tchau', phonetic: 'chow', translation: 'bye' },
      { text: 'sim', phonetic: 'seeng', translation: 'yes' },
      { text: 'não', phonetic: 'nowng', translation: 'no' },
      { text: 'água', phonetic: 'AH-gwah', translation: 'water' },
      { text: 'comida', phonetic: 'koh-MEE-dah', translation: 'food' },
      { text: 'casa', phonetic: 'KAH-zah', translation: 'house' },
      { text: 'amigo', phonetic: 'ah-MEE-goo', translation: 'friend' },
      { text: 'desculpe', phonetic: 'desh-KOOL-pee', translation: 'sorry' },
    ],
    sentences: [
      { text: 'Como você está?', phonetic: 'KOH-moo voh-SEH ehs-TAH', translation: 'How are you?' },
      { text: 'Meu nome é João', phonetic: 'meh-oo NOH-mee eh zhoh-OWN', translation: 'My name is João' },
      { text: 'Eu não entendo', phonetic: 'eh-oo nowng ehn-TEHN-doo', translation: "I don't understand" },
      { text: 'Quanto custa?', phonetic: 'KWAHN-too KOOS-tah', translation: 'How much?' },
      { text: 'Boa noite', phonetic: 'BOH-ah NOY-chee', translation: 'Good night' },
      { text: 'Muito prazer', phonetic: 'MWEEN-too prah-ZEHR', translation: 'Nice to meet you' },
    ],
  },

  ru: {
    speechLang: 'ru-RU',
    ttsLang: 'ru-RU',
    alphabet: [
      { text: 'А', phonetic: 'ah', translation: 'A' },
      { text: 'Б', phonetic: 'beh', translation: 'B' },
      { text: 'В', phonetic: 'veh', translation: 'V' },
      { text: 'Г', phonetic: 'geh', translation: 'G' },
      { text: 'Д', phonetic: 'deh', translation: 'D' },
      { text: 'Е', phonetic: 'yeh', translation: 'Ye' },
      { text: 'Ж', phonetic: 'zheh', translation: 'Zh' },
      { text: 'З', phonetic: 'zeh', translation: 'Z' },
      { text: 'И', phonetic: 'ee', translation: 'I' },
      { text: 'К', phonetic: 'kah', translation: 'K' },
      { text: 'Л', phonetic: 'el', translation: 'L' },
      { text: 'М', phonetic: 'em', translation: 'M' },
      { text: 'Н', phonetic: 'en', translation: 'N' },
      { text: 'О', phonetic: 'oh', translation: 'O' },
      { text: 'П', phonetic: 'peh', translation: 'P' },
      { text: 'Р', phonetic: 'er', translation: 'R' },
      { text: 'С', phonetic: 'es', translation: 'S' },
      { text: 'Т', phonetic: 'teh', translation: 'T' },
      { text: 'У', phonetic: 'oo', translation: 'U' },
      { text: 'Ф', phonetic: 'ef', translation: 'F' },
      { text: 'Х', phonetic: 'khah', translation: 'Kh' },
      { text: 'Ц', phonetic: 'tseh', translation: 'Ts' },
      { text: 'Ч', phonetic: 'cheh', translation: 'Ch' },
      { text: 'Ш', phonetic: 'shah', translation: 'Sh' },
      { text: 'Щ', phonetic: 'schah', translation: 'Shch' },
      { text: 'Э', phonetic: 'eh', translation: 'E' },
      { text: 'Ю', phonetic: 'yoo', translation: 'Yu' },
      { text: 'Я', phonetic: 'yah', translation: 'Ya' },
    ],
    words: [
      { text: 'привет', phonetic: 'pree-VYET', translation: 'hello' },
      { text: 'спасибо', phonetic: 'spah-SEE-bah', translation: 'thank you' },
      { text: 'да', phonetic: 'dah', translation: 'yes' },
      { text: 'нет', phonetic: 'nyet', translation: 'no' },
      { text: 'вода', phonetic: 'vah-DAH', translation: 'water' },
      { text: 'еда', phonetic: 'ye-DAH', translation: 'food' },
      { text: 'дом', phonetic: 'dom', translation: 'house' },
      { text: 'друг', phonetic: 'droog', translation: 'friend' },
      { text: 'хорошо', phonetic: 'khah-rah-SHOH', translation: 'good' },
      { text: 'пожалуйста', phonetic: 'pah-ZHAH-loo-stah', translation: 'please' },
      { text: 'книга', phonetic: 'KNEE-gah', translation: 'book' },
      { text: 'до свидания', phonetic: 'dah svee-DAH-nyah', translation: 'goodbye' },
    ],
    sentences: [
      { text: 'Как дела?', phonetic: 'kahk dee-LAH', translation: 'How are you?' },
      { text: 'Меня зовут Анна', phonetic: 'mee-NYAH zah-VOOT AH-nah', translation: 'My name is Anna' },
      { text: 'Я не понимаю', phonetic: 'yah nyeh pah-nee-MAH-yoo', translation: "I don't understand" },
      { text: 'Сколько это стоит?', phonetic: 'SKOL-kah EH-tah STOH-eet', translation: 'How much does this cost?' },
      { text: 'Доброе утро', phonetic: 'DOH-brah-yeh OO-trah', translation: 'Good morning' },
      { text: 'Спокойной ночи', phonetic: 'spah-KOY-nay NOH-chee', translation: 'Good night' },
    ],
  },

  zh: {
    speechLang: 'zh-CN',
    ttsLang: 'zh-CN',
    alphabet: [
      { text: '一', phonetic: 'yī', translation: 'one' },
      { text: '二', phonetic: 'èr', translation: 'two' },
      { text: '三', phonetic: 'sān', translation: 'three' },
      { text: '四', phonetic: 'sì', translation: 'four' },
      { text: '五', phonetic: 'wǔ', translation: 'five' },
      { text: '六', phonetic: 'liù', translation: 'six' },
      { text: '七', phonetic: 'qī', translation: 'seven' },
      { text: '八', phonetic: 'bā', translation: 'eight' },
      { text: '九', phonetic: 'jiǔ', translation: 'nine' },
      { text: '十', phonetic: 'shí', translation: 'ten' },
      { text: '人', phonetic: 'rén', translation: 'person' },
      { text: '大', phonetic: 'dà', translation: 'big' },
      { text: '小', phonetic: 'xiǎo', translation: 'small' },
      { text: '上', phonetic: 'shàng', translation: 'up/above' },
      { text: '下', phonetic: 'xià', translation: 'down/below' },
      { text: '中', phonetic: 'zhōng', translation: 'middle' },
    ],
    words: [
      { text: '你好', phonetic: 'nǐ hǎo', translation: 'hello' },
      { text: '谢谢', phonetic: 'xiè xie', translation: 'thank you' },
      { text: '是', phonetic: 'shì', translation: 'yes/is' },
      { text: '不', phonetic: 'bù', translation: 'no/not' },
      { text: '水', phonetic: 'shuǐ', translation: 'water' },
      { text: '吃', phonetic: 'chī', translation: 'eat' },
      { text: '家', phonetic: 'jiā', translation: 'home/family' },
      { text: '朋友', phonetic: 'péng yǒu', translation: 'friend' },
      { text: '好', phonetic: 'hǎo', translation: 'good' },
      { text: '再见', phonetic: 'zài jiàn', translation: 'goodbye' },
      { text: '爱', phonetic: 'ài', translation: 'love' },
      { text: '书', phonetic: 'shū', translation: 'book' },
    ],
    sentences: [
      { text: '你好吗？', phonetic: 'nǐ hǎo ma', translation: 'How are you?' },
      { text: '我叫李明', phonetic: 'wǒ jiào Lǐ Míng', translation: 'My name is Li Ming' },
      { text: '我不懂', phonetic: 'wǒ bù dǒng', translation: "I don't understand" },
      { text: '多少钱？', phonetic: 'duō shǎo qián', translation: 'How much money?' },
      { text: '早上好', phonetic: 'zǎo shang hǎo', translation: 'Good morning' },
      { text: '晚安', phonetic: 'wǎn ān', translation: 'Good night' },
      { text: '请说慢一点', phonetic: 'qǐng shuō màn yī diǎn', translation: 'Please speak slower' },
      { text: '谢谢你的帮助', phonetic: 'xiè xie nǐ de bāng zhù', translation: 'Thank you for your help' },
    ],
  },

  ja: {
    speechLang: 'ja-JP',
    ttsLang: 'ja-JP',
    alphabet: [
      { text: 'あ', phonetic: 'a', translation: 'A' },
      { text: 'い', phonetic: 'i', translation: 'I' },
      { text: 'う', phonetic: 'u', translation: 'U' },
      { text: 'え', phonetic: 'e', translation: 'E' },
      { text: 'お', phonetic: 'o', translation: 'O' },
      { text: 'か', phonetic: 'ka', translation: 'Ka' },
      { text: 'き', phonetic: 'ki', translation: 'Ki' },
      { text: 'く', phonetic: 'ku', translation: 'Ku' },
      { text: 'け', phonetic: 'ke', translation: 'Ke' },
      { text: 'こ', phonetic: 'ko', translation: 'Ko' },
      { text: 'さ', phonetic: 'sa', translation: 'Sa' },
      { text: 'し', phonetic: 'shi', translation: 'Shi' },
      { text: 'す', phonetic: 'su', translation: 'Su' },
      { text: 'せ', phonetic: 'se', translation: 'Se' },
      { text: 'そ', phonetic: 'so', translation: 'So' },
      { text: 'た', phonetic: 'ta', translation: 'Ta' },
      { text: 'な', phonetic: 'na', translation: 'Na' },
      { text: 'は', phonetic: 'ha', translation: 'Ha' },
      { text: 'ま', phonetic: 'ma', translation: 'Ma' },
      { text: 'ら', phonetic: 'ra', translation: 'Ra' },
    ],
    words: [
      { text: 'こんにちは', phonetic: 'kon-ni-chi-wa', translation: 'hello' },
      { text: 'ありがとう', phonetic: 'a-ri-ga-tou', translation: 'thank you' },
      { text: 'はい', phonetic: 'hai', translation: 'yes' },
      { text: 'いいえ', phonetic: 'ii-e', translation: 'no' },
      { text: '水', phonetic: 'mi-zu', translation: 'water' },
      { text: '食べ物', phonetic: 'ta-be-mo-no', translation: 'food' },
      { text: '家', phonetic: 'i-e', translation: 'house' },
      { text: '友達', phonetic: 'to-mo-da-chi', translation: 'friend' },
      { text: '本', phonetic: 'hon', translation: 'book' },
      { text: 'さようなら', phonetic: 'sa-you-na-ra', translation: 'goodbye' },
      { text: 'すみません', phonetic: 'su-mi-ma-sen', translation: 'excuse me' },
      { text: 'おはよう', phonetic: 'o-ha-you', translation: 'good morning' },
    ],
    sentences: [
      { text: 'お元気ですか？', phonetic: 'o-gen-ki de-su ka', translation: 'How are you?' },
      { text: '私の名前は田中です', phonetic: 'wa-ta-shi no na-mae wa Ta-na-ka de-su', translation: 'My name is Tanaka' },
      { text: 'わかりません', phonetic: 'wa-ka-ri-ma-sen', translation: "I don't understand" },
      { text: 'いくらですか？', phonetic: 'i-ku-ra de-su ka', translation: 'How much is it?' },
      { text: 'おやすみなさい', phonetic: 'o-ya-su-mi na-sai', translation: 'Good night' },
      { text: 'ゆっくり話してください', phonetic: 'yuk-ku-ri ha-na-shi-te ku-da-sai', translation: 'Please speak slowly' },
      { text: 'はじめまして', phonetic: 'ha-ji-me-ma-shi-te', translation: 'Nice to meet you' },
      { text: 'トイレはどこですか？', phonetic: 'toi-re wa do-ko de-su ka', translation: 'Where is the toilet?' },
    ],
  },

  id: {
    speechLang: 'id-ID',
    ttsLang: 'id-ID',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'beh', translation: 'B' },
      { text: 'C', phonetic: 'cheh', translation: 'C' },
      { text: 'D', phonetic: 'deh', translation: 'D' },
      { text: 'E', phonetic: 'eh', translation: 'E' },
      { text: 'F', phonetic: 'ef', translation: 'F' },
      { text: 'G', phonetic: 'geh', translation: 'G' },
      { text: 'H', phonetic: 'hah', translation: 'H' },
      { text: 'I', phonetic: 'ee', translation: 'I' },
      { text: 'J', phonetic: 'jeh', translation: 'J' },
      { text: 'K', phonetic: 'kah', translation: 'K' },
      { text: 'L', phonetic: 'el', translation: 'L' },
      { text: 'M', phonetic: 'em', translation: 'M' },
      { text: 'N', phonetic: 'en', translation: 'N' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'peh', translation: 'P' },
      { text: 'R', phonetic: 'er', translation: 'R' },
      { text: 'S', phonetic: 'es', translation: 'S' },
      { text: 'T', phonetic: 'teh', translation: 'T' },
      { text: 'U', phonetic: 'oo', translation: 'U' },
    ],
    words: [
      { text: 'halo', phonetic: 'HA-lo', translation: 'hello' },
      { text: 'terima kasih', phonetic: 'tuh-REE-mah KAH-see', translation: 'thank you' },
      { text: 'ya', phonetic: 'yah', translation: 'yes' },
      { text: 'tidak', phonetic: 'TEE-dak', translation: 'no' },
      { text: 'air', phonetic: 'ah-EER', translation: 'water' },
      { text: 'makanan', phonetic: 'mah-KAH-nan', translation: 'food' },
      { text: 'rumah', phonetic: 'ROO-mah', translation: 'house' },
      { text: 'teman', phonetic: 'tuh-MAHN', translation: 'friend' },
      { text: 'bagus', phonetic: 'BAH-goos', translation: 'good' },
      { text: 'selamat', phonetic: 'suh-LAH-mat', translation: 'greetings/safe' },
      { text: 'tolong', phonetic: 'TOH-long', translation: 'please/help' },
      { text: 'maaf', phonetic: 'MAH-af', translation: 'sorry' },
    ],
    sentences: [
      { text: 'Apa kabar?', phonetic: 'AH-pah KAH-bar', translation: 'How are you?' },
      { text: 'Nama saya Budi', phonetic: 'NAH-mah SAH-yah BOO-dee', translation: 'My name is Budi' },
      { text: 'Saya tidak mengerti', phonetic: 'SAH-yah TEE-dak mung-ER-tee', translation: "I don't understand" },
      { text: 'Berapa harganya?', phonetic: 'buh-RAH-pah har-GAH-nyah', translation: 'How much is it?' },
      { text: 'Selamat pagi', phonetic: 'suh-LAH-mat PAH-gee', translation: 'Good morning' },
      { text: 'Selamat malam', phonetic: 'suh-LAH-mat MAH-lam', translation: 'Good night' },
    ],
  },

  pcm: {
    speechLang: 'en-NG',
    ttsLang: 'en-NG',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'bee', translation: 'B' },
      { text: 'C', phonetic: 'see', translation: 'C' },
      { text: 'D', phonetic: 'dee', translation: 'D' },
      { text: 'E', phonetic: 'ee', translation: 'E' },
      { text: 'F', phonetic: 'ef', translation: 'F' },
      { text: 'G', phonetic: 'jee', translation: 'G' },
      { text: 'H', phonetic: 'aych', translation: 'H' },
      { text: 'I', phonetic: 'ai', translation: 'I' },
      { text: 'J', phonetic: 'jay', translation: 'J' },
      { text: 'K', phonetic: 'kay', translation: 'K' },
      { text: 'L', phonetic: 'el', translation: 'L' },
      { text: 'N', phonetic: 'en', translation: 'N' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'pee', translation: 'P' },
      { text: 'S', phonetic: 'es', translation: 'S' },
      { text: 'W', phonetic: 'double-u', translation: 'W' },
      { text: 'Y', phonetic: 'wai', translation: 'Y' },
    ],
    words: [
      { text: 'How far', phonetic: 'how fah', translation: 'hello / how are you' },
      { text: 'I dey', phonetic: 'ai dey', translation: "I'm fine" },
      { text: 'Wetin', phonetic: 'weh-tin', translation: 'what' },
      { text: 'Abeg', phonetic: 'ah-beg', translation: 'please' },
      { text: 'Wahala', phonetic: 'wah-HAH-lah', translation: 'trouble/problem' },
      { text: 'Chop', phonetic: 'chop', translation: 'eat/food' },
      { text: 'Oya', phonetic: 'OH-yah', translation: "let's go / come on" },
      { text: 'No wahala', phonetic: 'no wah-HAH-lah', translation: 'no problem' },
      { text: 'Dey go', phonetic: 'dey go', translation: 'going' },
      { text: 'Sabi', phonetic: 'SAH-bee', translation: 'know/understand' },
      { text: 'Pikin', phonetic: 'PEE-kin', translation: 'child' },
      { text: 'Abi', phonetic: 'AH-bee', translation: 'right? / or' },
    ],
    sentences: [
      { text: 'How you dey?', phonetic: 'how yoo dey', translation: 'How are you?' },
      { text: 'My name na Emeka', phonetic: 'mai naym na eh-MEH-kah', translation: 'My name is Emeka' },
      { text: 'I no understand', phonetic: 'ai no understand', translation: "I don't understand" },
      { text: 'How much e be?', phonetic: 'how much eh bee', translation: 'How much is it?' },
      { text: 'Good morning o', phonetic: 'good morning oh', translation: 'Good morning' },
      { text: 'Make we go', phonetic: 'mayk wee go', translation: "Let's go" },
    ],
  },

  it: {
    speechLang: 'it-IT',
    ttsLang: 'it-IT',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'bee', translation: 'B' },
      { text: 'C', phonetic: 'chee', translation: 'C' },
      { text: 'D', phonetic: 'dee', translation: 'D' },
      { text: 'E', phonetic: 'eh', translation: 'E' },
      { text: 'F', phonetic: 'EF-feh', translation: 'F' },
      { text: 'G', phonetic: 'jee', translation: 'G' },
      { text: 'H', phonetic: 'AHK-kah', translation: 'H' },
      { text: 'I', phonetic: 'ee', translation: 'I' },
      { text: 'L', phonetic: 'EL-leh', translation: 'L' },
      { text: 'M', phonetic: 'EM-meh', translation: 'M' },
      { text: 'N', phonetic: 'EN-neh', translation: 'N' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'pee', translation: 'P' },
      { text: 'Q', phonetic: 'koo', translation: 'Q' },
      { text: 'R', phonetic: 'ER-reh', translation: 'R' },
      { text: 'S', phonetic: 'ES-seh', translation: 'S' },
      { text: 'T', phonetic: 'tee', translation: 'T' },
      { text: 'U', phonetic: 'oo', translation: 'U' },
      { text: 'V', phonetic: 'voo', translation: 'V' },
      { text: 'Z', phonetic: 'DZEH-tah', translation: 'Z' },
    ],
    words: [
      { text: 'ciao', phonetic: 'CHOW', translation: 'hello/bye' },
      { text: 'grazie', phonetic: 'GRAH-tsyeh', translation: 'thank you' },
      { text: 'buongiorno', phonetic: 'bwon-JOHR-noh', translation: 'good morning' },
      { text: 'per favore', phonetic: 'pehr fah-VOH-reh', translation: 'please' },
      { text: 'arrivederci', phonetic: 'ah-ree-veh-DEHR-chee', translation: 'goodbye' },
      { text: 'sì', phonetic: 'see', translation: 'yes' },
      { text: 'no', phonetic: 'noh', translation: 'no' },
      { text: 'acqua', phonetic: 'AHK-kwah', translation: 'water' },
      { text: 'casa', phonetic: 'KAH-sah', translation: 'house' },
      { text: 'amico', phonetic: 'ah-MEE-koh', translation: 'friend' },
      { text: 'buono', phonetic: 'BWOH-noh', translation: 'good' },
      { text: 'scusa', phonetic: 'SKOO-zah', translation: 'excuse me' },
    ],
    sentences: [
      { text: 'Come stai?', phonetic: 'KOH-meh STAH-ee', translation: 'How are you?' },
      { text: 'Mi chiamo Marco', phonetic: 'mee KYAH-moh MAHR-koh', translation: 'My name is Marco' },
      { text: 'Non capisco', phonetic: 'non kah-PEE-skoh', translation: "I don't understand" },
      { text: 'Quanto costa?', phonetic: 'KWAHN-toh KOS-tah', translation: 'How much does it cost?' },
      { text: 'Buona notte', phonetic: 'BWOH-nah NOT-teh', translation: 'Good night' },
      { text: 'Piacere di conoscerti', phonetic: 'pyah-CHEH-reh dee koh-NOH-sher-tee', translation: 'Nice to meet you' },
    ],
  },

  th: {
    speechLang: 'th-TH',
    ttsLang: 'th-TH',
    alphabet: [
      { text: 'ก', phonetic: 'gaw gai', translation: 'G (chicken)' },
      { text: 'ข', phonetic: 'kaw kai', translation: 'K (egg)' },
      { text: 'ค', phonetic: 'kaw kwaai', translation: 'K (buffalo)' },
      { text: 'ง', phonetic: 'ngaw ngoo', translation: 'Ng (snake)' },
      { text: 'จ', phonetic: 'jaw jaan', translation: 'J (plate)' },
      { text: 'ช', phonetic: 'chaw chaang', translation: 'Ch (elephant)' },
      { text: 'ด', phonetic: 'daw dek', translation: 'D (child)' },
      { text: 'ต', phonetic: 'taw tao', translation: 'T (turtle)' },
      { text: 'น', phonetic: 'naw noo', translation: 'N (mouse)' },
      { text: 'บ', phonetic: 'baw bai-mai', translation: 'B (leaf)' },
      { text: 'ป', phonetic: 'paw plaa', translation: 'P (fish)' },
      { text: 'ม', phonetic: 'maw maa', translation: 'M (horse)' },
      { text: 'ร', phonetic: 'raw reua', translation: 'R (boat)' },
      { text: 'ล', phonetic: 'law ling', translation: 'L (monkey)' },
      { text: 'ว', phonetic: 'waw waen', translation: 'W (ring)' },
      { text: 'ส', phonetic: 'saw seua', translation: 'S (tiger)' },
      { text: 'ห', phonetic: 'haw heep', translation: 'H (chest)' },
      { text: 'อ', phonetic: 'aw aang', translation: 'O (basin)' },
    ],
    words: [
      { text: 'สวัสดี', phonetic: 'sa-wat-DEE', translation: 'hello' },
      { text: 'ขอบคุณ', phonetic: 'kop-KOON', translation: 'thank you' },
      { text: 'ใช่', phonetic: 'chai', translation: 'yes' },
      { text: 'ไม่', phonetic: 'mai', translation: 'no' },
      { text: 'น้ำ', phonetic: 'naam', translation: 'water' },
      { text: 'อาหาร', phonetic: 'aa-HAAN', translation: 'food' },
      { text: 'บ้าน', phonetic: 'baan', translation: 'house' },
      { text: 'เพื่อน', phonetic: 'peuan', translation: 'friend' },
      { text: 'ดี', phonetic: 'dee', translation: 'good' },
      { text: 'ครับ/ค่ะ', phonetic: 'krap/ka', translation: 'polite particle (m/f)' },
      { text: 'ขอโทษ', phonetic: 'kor-TOHT', translation: 'sorry' },
      { text: 'อร่อย', phonetic: 'a-ROY', translation: 'delicious' },
    ],
    sentences: [
      { text: 'สบายดีไหม?', phonetic: 'sa-bai dee mai', translation: 'How are you?' },
      { text: 'ผม/ฉันชื่อสมชาย', phonetic: 'pom/chan cheu Som-chai', translation: 'My name is Somchai' },
      { text: 'ไม่เข้าใจ', phonetic: 'mai kao jai', translation: "I don't understand" },
      { text: 'ราคาเท่าไหร่?', phonetic: 'raa-kaa tao-rai', translation: 'How much is it?' },
      { text: 'อรุณสวัสดิ์', phonetic: 'a-run sa-wat', translation: 'Good morning' },
      { text: 'ราตรีสวัสดิ์', phonetic: 'raa-tree sa-wat', translation: 'Good night' },
    ],
  },

  tr: {
    speechLang: 'tr-TR',
    ttsLang: 'tr-TR',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'beh', translation: 'B' },
      { text: 'C', phonetic: 'jeh', translation: 'C (like J)' },
      { text: 'Ç', phonetic: 'cheh', translation: 'Ç (Ch)' },
      { text: 'D', phonetic: 'deh', translation: 'D' },
      { text: 'E', phonetic: 'eh', translation: 'E' },
      { text: 'F', phonetic: 'feh', translation: 'F' },
      { text: 'G', phonetic: 'geh', translation: 'G' },
      { text: 'Ğ', phonetic: 'yoo-moo-shak geh', translation: 'Ğ (soft G)' },
      { text: 'H', phonetic: 'heh', translation: 'H' },
      { text: 'I', phonetic: 'uh', translation: 'I (undotted)' },
      { text: 'İ', phonetic: 'ee', translation: 'İ (dotted)' },
      { text: 'K', phonetic: 'keh', translation: 'K' },
      { text: 'L', phonetic: 'leh', translation: 'L' },
      { text: 'M', phonetic: 'meh', translation: 'M' },
      { text: 'N', phonetic: 'neh', translation: 'N' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'Ö', phonetic: 'uh (rounded)', translation: 'Ö' },
      { text: 'P', phonetic: 'peh', translation: 'P' },
      { text: 'R', phonetic: 'reh', translation: 'R' },
      { text: 'S', phonetic: 'seh', translation: 'S' },
      { text: 'Ş', phonetic: 'sheh', translation: 'Ş (Sh)' },
      { text: 'T', phonetic: 'teh', translation: 'T' },
      { text: 'U', phonetic: 'oo', translation: 'U' },
      { text: 'Ü', phonetic: 'ew', translation: 'Ü' },
    ],
    words: [
      { text: 'merhaba', phonetic: 'mer-HA-ba', translation: 'hello' },
      { text: 'teşekkür ederim', phonetic: 'te-shek-KEUR eh-deh-REEM', translation: 'thank you' },
      { text: 'evet', phonetic: 'eh-VET', translation: 'yes' },
      { text: 'hayır', phonetic: 'ha-YUHR', translation: 'no' },
      { text: 'su', phonetic: 'soo', translation: 'water' },
      { text: 'yemek', phonetic: 'yeh-MEK', translation: 'food' },
      { text: 'ev', phonetic: 'ev', translation: 'house' },
      { text: 'arkadaş', phonetic: 'ar-ka-DASH', translation: 'friend' },
      { text: 'güzel', phonetic: 'gew-ZEL', translation: 'beautiful/good' },
      { text: 'lütfen', phonetic: 'LEWT-fen', translation: 'please' },
      { text: 'günaydın', phonetic: 'gew-nai-DUN', translation: 'good morning' },
      { text: 'hoşça kal', phonetic: 'hosh-CHA kal', translation: 'goodbye' },
    ],
    sentences: [
      { text: 'Nasılsınız?', phonetic: 'na-SUL-suh-nuz', translation: 'How are you?' },
      { text: 'Benim adım Ali', phonetic: 'beh-NIM ah-DUM ah-LEE', translation: 'My name is Ali' },
      { text: 'Anlamıyorum', phonetic: 'an-la-MUH-yo-room', translation: "I don't understand" },
      { text: 'Bu ne kadar?', phonetic: 'boo neh ka-DAR', translation: 'How much is this?' },
      { text: 'İyi geceler', phonetic: 'ee-YEE geh-jeh-LER', translation: 'Good night' },
      { text: 'Memnun oldum', phonetic: 'mem-NOON ol-DOOM', translation: 'Nice to meet you' },
    ],
  },

  fil: {
    speechLang: 'fil-PH',
    ttsLang: 'fil-PH',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'bah', translation: 'B' },
      { text: 'K', phonetic: 'kah', translation: 'K' },
      { text: 'D', phonetic: 'dah', translation: 'D' },
      { text: 'E', phonetic: 'eh', translation: 'E' },
      { text: 'G', phonetic: 'gah', translation: 'G' },
      { text: 'H', phonetic: 'hah', translation: 'H' },
      { text: 'I', phonetic: 'ee', translation: 'I' },
      { text: 'L', phonetic: 'lah', translation: 'L' },
      { text: 'M', phonetic: 'mah', translation: 'M' },
      { text: 'N', phonetic: 'nah', translation: 'N' },
      { text: 'NG', phonetic: 'ngah', translation: 'Ng' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'pah', translation: 'P' },
      { text: 'R', phonetic: 'rah', translation: 'R' },
      { text: 'S', phonetic: 'sah', translation: 'S' },
      { text: 'T', phonetic: 'tah', translation: 'T' },
      { text: 'U', phonetic: 'oo', translation: 'U' },
      { text: 'W', phonetic: 'wah', translation: 'W' },
      { text: 'Y', phonetic: 'yah', translation: 'Y' },
    ],
    words: [
      { text: 'kamusta', phonetic: 'ka-MOOS-ta', translation: 'hello / how are you' },
      { text: 'salamat', phonetic: 'sa-LA-mat', translation: 'thank you' },
      { text: 'oo', phonetic: 'oh-oh', translation: 'yes' },
      { text: 'hindi', phonetic: 'hin-DEE', translation: 'no' },
      { text: 'tubig', phonetic: 'TOO-big', translation: 'water' },
      { text: 'pagkain', phonetic: 'pag-KA-in', translation: 'food' },
      { text: 'bahay', phonetic: 'BA-hai', translation: 'house' },
      { text: 'kaibigan', phonetic: 'kai-BEE-gan', translation: 'friend' },
      { text: 'maganda', phonetic: 'ma-gan-DA', translation: 'beautiful' },
      { text: 'mabuti', phonetic: 'ma-BOO-tee', translation: 'good/fine' },
      { text: 'paalam', phonetic: 'pa-A-lam', translation: 'goodbye' },
      { text: 'mahal', phonetic: 'ma-HAL', translation: 'love/expensive' },
    ],
    sentences: [
      { text: 'Kamusta ka?', phonetic: 'ka-MOOS-ta ka', translation: 'How are you?' },
      { text: 'Ako si Maria', phonetic: 'a-KO see Ma-RI-a', translation: 'I am Maria' },
      { text: 'Hindi ko maintindihan', phonetic: 'hin-DEE ko ma-in-tin-di-HAN', translation: "I don't understand" },
      { text: 'Magkano ito?', phonetic: 'mag-KA-no ee-TO', translation: 'How much is this?' },
      { text: 'Magandang umaga', phonetic: 'ma-gan-DANG oo-MA-ga', translation: 'Good morning' },
      { text: 'Magandang gabi', phonetic: 'ma-gan-DANG GA-bee', translation: 'Good evening' },
    ],
  },

  ko: {
    speechLang: 'ko-KR',
    ttsLang: 'ko-KR',
    alphabet: [
      { text: 'ㄱ', phonetic: 'giyeok', translation: 'G/K' },
      { text: 'ㄴ', phonetic: 'nieun', translation: 'N' },
      { text: 'ㄷ', phonetic: 'digeut', translation: 'D/T' },
      { text: 'ㄹ', phonetic: 'rieul', translation: 'R/L' },
      { text: 'ㅁ', phonetic: 'mieum', translation: 'M' },
      { text: 'ㅂ', phonetic: 'bieup', translation: 'B/P' },
      { text: 'ㅅ', phonetic: 'siot', translation: 'S' },
      { text: 'ㅇ', phonetic: 'ieung', translation: 'silent/Ng' },
      { text: 'ㅈ', phonetic: 'jieut', translation: 'J' },
      { text: 'ㅊ', phonetic: 'chieut', translation: 'Ch' },
      { text: 'ㅋ', phonetic: 'kieuk', translation: 'K' },
      { text: 'ㅌ', phonetic: 'tieut', translation: 'T' },
      { text: 'ㅍ', phonetic: 'pieup', translation: 'P' },
      { text: 'ㅎ', phonetic: 'hieut', translation: 'H' },
      { text: 'ㅏ', phonetic: 'a', translation: 'A' },
      { text: 'ㅓ', phonetic: 'eo', translation: 'Eo' },
      { text: 'ㅗ', phonetic: 'o', translation: 'O' },
      { text: 'ㅜ', phonetic: 'u', translation: 'U' },
      { text: 'ㅡ', phonetic: 'eu', translation: 'Eu' },
      { text: 'ㅣ', phonetic: 'i', translation: 'I' },
    ],
    words: [
      { text: '안녕하세요', phonetic: 'an-nyeong-ha-se-yo', translation: 'hello' },
      { text: '감사합니다', phonetic: 'gam-sa-ham-ni-da', translation: 'thank you' },
      { text: '네', phonetic: 'ne', translation: 'yes' },
      { text: '아니요', phonetic: 'a-ni-yo', translation: 'no' },
      { text: '물', phonetic: 'mul', translation: 'water' },
      { text: '음식', phonetic: 'eum-sik', translation: 'food' },
      { text: '집', phonetic: 'jip', translation: 'house' },
      { text: '친구', phonetic: 'chin-gu', translation: 'friend' },
      { text: '좋은', phonetic: 'jo-eun', translation: 'good' },
      { text: '안녕히 가세요', phonetic: 'an-nyeong-hi ga-se-yo', translation: 'goodbye' },
      { text: '죄송합니다', phonetic: 'joe-song-ham-ni-da', translation: 'sorry' },
      { text: '사랑', phonetic: 'sa-rang', translation: 'love' },
    ],
    sentences: [
      { text: '잘 지내세요?', phonetic: 'jal ji-nae-se-yo', translation: 'How are you?' },
      { text: '제 이름은 민수입니다', phonetic: 'je i-reum-eun Min-su-im-ni-da', translation: 'My name is Minsu' },
      { text: '이해가 안 돼요', phonetic: 'i-hae-ga an dwae-yo', translation: "I don't understand" },
      { text: '얼마예요?', phonetic: 'eol-ma-ye-yo', translation: 'How much is it?' },
      { text: '좋은 아침이에요', phonetic: 'jo-eun a-chim-i-e-yo', translation: 'Good morning' },
      { text: '안녕히 주무세요', phonetic: 'an-nyeong-hi ju-mu-se-yo', translation: 'Good night' },
    ],
  },

  de: {
    speechLang: 'de-DE',
    ttsLang: 'de-DE',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'beh', translation: 'B' },
      { text: 'C', phonetic: 'tseh', translation: 'C' },
      { text: 'D', phonetic: 'deh', translation: 'D' },
      { text: 'E', phonetic: 'eh', translation: 'E' },
      { text: 'F', phonetic: 'ef', translation: 'F' },
      { text: 'G', phonetic: 'geh', translation: 'G' },
      { text: 'H', phonetic: 'hah', translation: 'H' },
      { text: 'I', phonetic: 'ee', translation: 'I' },
      { text: 'J', phonetic: 'yot', translation: 'J' },
      { text: 'K', phonetic: 'kah', translation: 'K' },
      { text: 'L', phonetic: 'el', translation: 'L' },
      { text: 'M', phonetic: 'em', translation: 'M' },
      { text: 'N', phonetic: 'en', translation: 'N' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'peh', translation: 'P' },
      { text: 'Q', phonetic: 'koo', translation: 'Q' },
      { text: 'R', phonetic: 'air', translation: 'R' },
      { text: 'S', phonetic: 'es', translation: 'S' },
      { text: 'T', phonetic: 'teh', translation: 'T' },
      { text: 'U', phonetic: 'oo', translation: 'U' },
      { text: 'Ä', phonetic: 'eh (umlaut)', translation: 'Ä' },
      { text: 'Ö', phonetic: 'uh (umlaut)', translation: 'Ö' },
      { text: 'Ü', phonetic: 'ew (umlaut)', translation: 'Ü' },
      { text: 'ß', phonetic: 'es-tset', translation: 'ß (sharp S)' },
    ],
    words: [
      { text: 'hallo', phonetic: 'HA-loh', translation: 'hello' },
      { text: 'danke', phonetic: 'DAHN-keh', translation: 'thank you' },
      { text: 'ja', phonetic: 'yah', translation: 'yes' },
      { text: 'nein', phonetic: 'nine', translation: 'no' },
      { text: 'Wasser', phonetic: 'VAH-ser', translation: 'water' },
      { text: 'Essen', phonetic: 'EH-sen', translation: 'food' },
      { text: 'Haus', phonetic: 'house', translation: 'house' },
      { text: 'Freund', phonetic: 'froynt', translation: 'friend' },
      { text: 'gut', phonetic: 'goot', translation: 'good' },
      { text: 'bitte', phonetic: 'BIT-teh', translation: 'please' },
      { text: 'tschüss', phonetic: 'chews', translation: 'bye' },
      { text: 'Entschuldigung', phonetic: 'ent-SHOOL-dee-goong', translation: 'excuse me' },
    ],
    sentences: [
      { text: 'Wie geht es Ihnen?', phonetic: 'vee gayt es EE-nen', translation: 'How are you?' },
      { text: 'Ich heiße Hans', phonetic: 'ikh HY-seh Hahns', translation: 'My name is Hans' },
      { text: 'Ich verstehe nicht', phonetic: 'ikh fer-SHTEH-eh nikht', translation: "I don't understand" },
      { text: 'Wie viel kostet das?', phonetic: 'vee feel KOS-tet dahs', translation: 'How much does this cost?' },
      { text: 'Guten Morgen', phonetic: 'GOO-ten MOR-gen', translation: 'Good morning' },
      { text: 'Gute Nacht', phonetic: 'GOO-teh nahkht', translation: 'Good night' },
    ],
  },

  sw: {
    speechLang: 'sw-KE',
    ttsLang: 'sw-KE',
    alphabet: [
      { text: 'A', phonetic: 'ah', translation: 'A' },
      { text: 'B', phonetic: 'bee', translation: 'B' },
      { text: 'CH', phonetic: 'chee', translation: 'Ch' },
      { text: 'D', phonetic: 'dee', translation: 'D' },
      { text: 'E', phonetic: 'eh', translation: 'E' },
      { text: 'F', phonetic: 'ef', translation: 'F' },
      { text: 'G', phonetic: 'gee', translation: 'G' },
      { text: 'H', phonetic: 'aitch', translation: 'H' },
      { text: 'I', phonetic: 'ee', translation: 'I' },
      { text: 'J', phonetic: 'jay', translation: 'J' },
      { text: 'K', phonetic: 'kay', translation: 'K' },
      { text: 'L', phonetic: 'el', translation: 'L' },
      { text: 'M', phonetic: 'em', translation: 'M' },
      { text: 'N', phonetic: 'en', translation: 'N' },
      { text: 'O', phonetic: 'oh', translation: 'O' },
      { text: 'P', phonetic: 'pee', translation: 'P' },
      { text: 'R', phonetic: 'ar', translation: 'R' },
      { text: 'S', phonetic: 'es', translation: 'S' },
      { text: 'T', phonetic: 'tee', translation: 'T' },
      { text: 'U', phonetic: 'oo', translation: 'U' },
      { text: 'W', phonetic: 'wee', translation: 'W' },
      { text: 'Y', phonetic: 'yee', translation: 'Y' },
      { text: 'Z', phonetic: 'zed', translation: 'Z' },
    ],
    words: [
      { text: 'jambo', phonetic: 'JAM-bo', translation: 'hello' },
      { text: 'asante', phonetic: 'ah-SAN-teh', translation: 'thank you' },
      { text: 'ndiyo', phonetic: 'n-DEE-yo', translation: 'yes' },
      { text: 'hapana', phonetic: 'ha-PA-na', translation: 'no' },
      { text: 'maji', phonetic: 'MA-jee', translation: 'water' },
      { text: 'chakula', phonetic: 'cha-KOO-la', translation: 'food' },
      { text: 'nyumba', phonetic: 'NYOOM-ba', translation: 'house' },
      { text: 'rafiki', phonetic: 'ra-FEE-kee', translation: 'friend' },
      { text: 'nzuri', phonetic: 'n-ZOO-ree', translation: 'good/beautiful' },
      { text: 'tafadhali', phonetic: 'ta-fa-DHA-lee', translation: 'please' },
      { text: 'kwaheri', phonetic: 'kwa-HEH-ree', translation: 'goodbye' },
      { text: 'pole', phonetic: 'POH-leh', translation: 'sorry' },
    ],
    sentences: [
      { text: 'Habari yako?', phonetic: 'ha-BA-ree YA-ko', translation: 'How are you?' },
      { text: 'Jina langu ni Amina', phonetic: 'JEE-na LAN-goo nee a-MEE-na', translation: 'My name is Amina' },
      { text: 'Sielewi', phonetic: 'see-eh-LEH-wee', translation: "I don't understand" },
      { text: 'Bei gani?', phonetic: 'BEH-ee GA-nee', translation: 'How much?' },
      { text: 'Habari za asubuhi', phonetic: 'ha-BA-ree za a-SOO-boo-hee', translation: 'Good morning' },
      { text: 'Usiku mwema', phonetic: 'oo-SEE-koo MWEH-ma', translation: 'Good night' },
    ],
  },
};

// Get pronunciation data for a language code, with fallback
export function getPronunciationData(languageCode: string): LanguagePronunciationData | null {
  return PRONUNCIATION_DATA[languageCode] || null;
}

// Get speech recognition language code
export function getSpeechLang(languageCode: string): string {
  return PRONUNCIATION_DATA[languageCode]?.speechLang || 'en-US';
}

// Get TTS language code
export function getTTSLang(languageCode: string): string {
  return PRONUNCIATION_DATA[languageCode]?.ttsLang || 'en-US';
}
